### ISSUE TITLE
Shots fired doesnt work

### ISSUE THREAD

**Issue by georgikens** [SuiMachine/HitmanStatisticsUber#3]
the Shots Fired meter stays at 0 no matter what I do. i know this is an old project but I would love it to be fixed.

**Comment by Alex-Winchester** [comment]
yeah in hitman 2 silent assassin the shots fire is not counting,
Which makes it a bit hard to tell if we still have silent assassin or if its ruined,
Please watch this video to verify what we are talking about https://www.youtube.com/watch?v=T0o-QV9adh8

**Comment by Abdulsarhan** [comment]
I fixed this. Please merge my PR.
